# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x01000000450d958838c51d88c532c934bb3943e09b3e08ef12c2b4eb9b1670ce"
    chainName: cardanopreview
    connections:
      - token: ethereum|sepolia|0x127ab2b2c5b8d9ae757c8cf0c3fe76c5ede49f78
    decimals: 6
    logoURI: /deployments/warp_routes/wADA/logo.svg
    name: Cardano
    standard: CardanoHypNative
    symbol: ADA
  - addressOrDenom: "0x127ab2b2c5b8d9ae757c8cf0c3fe76c5ede49f78"
    chainName: sepolia
    connections:
      - token: cardano|cardanopreview|0x01000000450d958838c51d88c532c934bb3943e09b3e08ef12c2b4eb9b1670ce
    decimals: 6
    logoURI: /deployments/warp_routes/wADA/logo.svg
    name: Wrapped ADA
    standard: EvmHypSynthetic
    symbol: wADA
