# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x01000000bfbfd7ab59492bd6b3a4a77a6f00774145d43f306a9bf326f74da44c"
    chainName: cardanopreview
    connections:
      - token: ethereum|sepolia|0x7b1604c4696d781fd06be96e0f0da369058b3cb5
    decimals: 6
    logoURI: /deployments/warp_routes/wADA/logo.svg
    name: Cardano
    standard: CardanoHypNative
    symbol: ADA
  - addressOrDenom: "0x7b1604c4696d781fd06be96e0f0da369058b3cb5"
    chainName: sepolia
    connections:
      - token: cardano|cardanopreview|0x01000000bfbfd7ab59492bd6b3a4a77a6f00774145d43f306a9bf326f74da44c
    decimals: 6
    logoURI: /deployments/warp_routes/wADA/logo.svg
    name: Wrapped ADA
    standard: EvmHypSynthetic
    symbol: wADA
