# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x01000000ed08f892a125915b483cd7547a2f9dfbf0531b21ec7389110bedfc2f"
    chainName: cardanopreview
    connections:
      - token: midnight|midnight|0x25a367845fb5ae5ed5ee1524822f206ab5fd54fc59c85b616b7ebae375d978c9
    decimals: 6
    scale: 1000000000000
    logoURI: /deployments/warp_routes/NIGHT/sNIGHT-logo.svg
    name: Synthetic NIGHT
    standard: CardanoHypSynthetic
    symbol: sNIGHT
  - addressOrDenom: "0x25a367845fb5ae5ed5ee1524822f206ab5fd54fc59c85b616b7ebae375d978c9"
    chainName: midnight
    connections:
      - token: cardano|cardanopreview|0x01000000ed08f892a125915b483cd7547a2f9dfbf0531b21ec7389110bedfc2f
    decimals: 6
    scale: 1000000000000
    logoURI: /deployments/warp_routes/NIGHT/logo.svg
    name: NIGHT
    standard: MidnightHypNative
    symbol: NIGHT
