# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: b424d62e725fe615576e948b675d21ae7ddb9fc8f97d179d4bc5edaf1f016790
    chainName: midnight
    igpTokenAddressOrDenom: 5a29bf11d6ac29d923f955ebd27171232433d65cdb176d780f2be17da4df8491
    connections:
      - token: ethereum|sepolia|0x1F7FA3bFC565a7a31C1A44EF928DB04f162a84Fb
    decimals: 6
    name: NIGHT
    standard: MidnightHypNative
    symbol: sNIGHT
    tokenType: native
  - addressOrDenom: "0x1F7FA3bFC565a7a31C1A44EF928DB04f162a84Fb"
    chainName: sepolia
    connections:
      - token: midnight|midnight|b424d62e725fe615576e948b675d21ae7ddb9fc8f97d179d4bc5edaf1f016790
    decimals: 18
    name: NIGHT
    standard: EvmHypSynthetic
    symbol: sNIGHT
    tokenType: synthetic
