# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x25a367845fb5ae5ed5ee1524822f206ab5fd54fc59c85b616b7ebae375d978c9"
    chainName: midnight
    connections:
      - token: ethereum|sepolia|0x7b68c3aedce988c38509310c6545ee22d789aaf0
    decimals: 6
    logoURI: /deployments/warp_routes/NIGHT/logo.svg
    name: NIGHT
    scale: 1000000000000
    standard: MidnightHypNative
    symbol: NIGHT
  - addressOrDenom: "0x7b68c3aedce988c38509310c6545ee22d789aaf0"
    chainName: sepolia
    connections:
      - token: midnight|midnight|0x25a367845fb5ae5ed5ee1524822f206ab5fd54fc59c85b616b7ebae375d978c9
    decimals: 18
    logoURI: /deployments/warp_routes/NIGHT/logo.svg
    name: Stagenet NIGHT
    standard: EvmHypSynthetic
    symbol: sNIGHT
